@startuml

participant UART
participant "Data Link Layer" as DL
participant "Network Layer" as NL
participant Client as C
actor Actor as A

UART -> DL: receivedBufferCallback
activate DL

DL -> NL: receiveFrameCallback
deactivate DL
activate NL

NL -> C: receivedPacketCallback
deactivate NL
activate C

C -> A: commandCallback
rnote over A: process\nrequest
deactivate C

A -> C: reply
activate C

C -> NL: sendReplyPacket
deactivate C
activate NL

NL -> DL: sendFrame
deactivate NL
activate DL

DL -> UART: sendBuffer
deactivate DL

@enduml
