name: CI

on:
  pull_request:
    branches: [ kinetic-devel ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: shadowrobot/build-tools:xenial-kinetic

    steps:
      - uses: actions/checkout@v2

      - name: Build Project
        run: |
          wget -O /tmp/script.sh "$remote_shell_script" 
          chmod 755 /tmp/script.sh
          bash /tmp/script.sh "$toolset_branch" $server_type $used_modules $relative_job_path
        env:
          FIRST_NAME: Mona
          toolset_branch: master
          server_type: local
          ros_release_name: kinetic
          ubuntu_version_name: xenial
          used_modules: check_cache,check_build,code_coverage
          relative_job_path: ${{ env.GITHUB_WORKSPACE }}
          unit_tests_result_dir: "${{ env.GITHUB_WORKSPACE }}/unit_tests"
          coverage_tests_result_dir: "${{ env.GITHUB_WORKSPACE }}/code_coverage"
          remote_shell_script: 'https://raw.githubusercontent.com/shadow-robot/sr-build-tools/master/bin/sr-run-ci-build.sh'
